[tool]
[tool.commitizen]
name = "cz_conventional_commits"
version = "0.0.1"
tag_format = "$version"
version_files = [
    "src/__init__.py:__version__",
    "setup.cfg:version",
    "pyproject.toml:version"
]