version: '3.8'

services:
  
  database:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - TZ=GMT+3
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=auth_user